# Generated by Django 4.1.2 on 2022-12-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0004_dislike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_added_Websites',
            new_name='User_added_Website',
        ),
    ]
