# Generated by Django 4.1.2 on 2022-12-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0005_rename_user_added_websites_user_added_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_added_website',
            name='website_id',
        ),
    ]
