# Generated by Django 4.1.2 on 2022-12-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0007_delete_user_added_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='User_added_Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCheckerApp.user')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCheckerApp.websitemodel')),
            ],
        ),
    ]
