# Generated by Django 4.1.2 on 2022-12-12 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0010_like_website_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webCheckerApp.websitemodel'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webCheckerApp.user'),
        ),
    ]
