# Generated by Django 4.1.2 on 2022-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0011_dislike_website_alter_dislike_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisLike',
        ),
    ]
