# Generated by Django 4.1.2 on 2022-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0012_delete_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_or_dislike',
            field=models.IntegerField(default=0),
        ),
    ]
