# Generated by Django 4.1.2 on 2022-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0013_like_like_or_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemodel',
            name='total_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
