# Generated by Django 4.1.2 on 2022-12-14 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCheckerApp', '0014_websitemodel_total_dislikes_websitemodel_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 18, 50, 11, 669630, tzinfo=datetime.timezone.utc)),
        ),
    ]
